# Jekyll's site settings
# https://jekyllrb.com/docs/configuration/

# Plugins
plugins:
  # https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Location
source: src/
# This is the default for use by `jekyll serve` and other `jekyll`
# commands used during local development. We set "public_html/"
# only for the production output. This way there is no chance of
# accidentally committing the development version.
destination: src/_site/

# Output
permalink: pretty
